---
- name: Install Underpass
  hosts: control
  become: true

  vars_files:
    - "./ansible/vars/vars.yml"

  roles:
    - role: geerlingguy.docker
      tags: [ 'install-docker' ]

  tasks:
    - include_tasks: ./ansible/playbooks/setup-centos.yml
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
      tags: [ 'playbook-centos' ]

    - include_tasks: ./ansible/playbooks/setup-rpi.yml
      when: ansible_distribution == 'raspbian' and ansible_distribution_release == 'buster'
      tags: [ 'playbook-raspbian' ]

    - include_tasks: ./ansible/playbooks/setup-debian.yml
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '10'
      tags: [ 'playbook-debian' ]

    - include_tasks: ./ansible/playbooks/setup-ubuntu.yml
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version = '18.04'
      tags: [ 'playbook-ubuntu' ]

    - include: ./ansible/playbooks/control.yml
      tags: [ 'playbook-control' ]
