---
- name: Install Underpass
  hosts: control
  become: true

  vars_files:
    - "./ansible/vars/vars.yml"

  roles:
    - role: geerlingguy.docker
      tags: [ 'install-docker' ]

  tasks:
    - include_tasks: ./ansible/playbooks/setup-centos.yml
      when: ansible_distribution == 'CentOS'
      tags: [ 'playbook-centos' ]
    
    - include_tasks: ./ansible/playbooks/setup-ubuntu.yml
      when: ansible_distribution == 'Ubuntu'
      tags: [ 'playbook-ubuntu' ]

    - include: ./ansible/playbooks/setup-rpi.yml
      when: ansible_distribution == 'Raspbian'
      tags: [ 'playbook-rpi' ]

    - include: ./ansible/playbooks/control.yml
      tags: [ 'playbook-control' ]

