---
# tasks: (continuation)
    - name: Set Nano Environment
      lineinfile:
        path: ~/.nanorc
        line: "include \"/usr/share/nano/sh.nanorc\""
        create: yes
      tags: [ 'config-nano']

    - name: Add Nano to Bash Profile
      lineinfile:
        path: ~/.bashrc
        insertafter: 'EOF'
        line: "export VISUAL=nano"
      tags: [ 'config-nano']

    - name: Insert Public IP to Squid Config
      lineinfile:
        path: /opt/underpass/config/squid/squid.conf
        regexp: '^acl SSH dst'
        line: "acl SSH dst {{ ansible_eth0.ipv4.address }}-{{ ansible_eth0.ipv4.address }}/32"
      tags: [ 'squid-ip' ]

