---
#  tasks: (continuation)
    - name: Install System Tools
      apt:
        name: ['firewalld', 'glances', 'htop', 'ncdu', 'ntp', 'screen', 'telnet']
        state: present
        update_cache: yes
      tags: [ 'apt-sys-tools' ]

    - name: Install Fail2Ban
      apt:
        name: fail2ban
        state: present
        update_cache: yes
      tags: [ 'fail2ban' ]

    - name: Configure Fail2Ban
      copy:
        src: /opt/underpass/config/fail2ban/jail-debian.local
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: '644'
      tags: [ 'fail2ban' ]

    - name: Restart Fail2Ban
      service:
        name: fail2ban
        state: restarted
      tags: [ 'fail2ban' ]

    - name: Ensure Firewalld is Restarted
      service:
        name: firewalld
        state: restarted
      tags: [ 'restart-firewall' ]

    - name: Sleep For a While
      wait_for:
        timeout: 10
      tags: [ 'sleep' ]

    - name: Add Squid and Dante SOCKS Default Ports to Firewall
      command: "{{ item }}"
      with_items:
        - "iptables -F"
        - "firewall-cmd --set-default-zone=public"
        - "firewall-cmd --zone=public --add-service=squid --permanent"
        - "firewall-cmd --zone=public --add-port=1080/tcp --permanent"
        - "firewall-cmd --reload"
      tags: [ 'restart-firewall' ]

    - name: Ensure Docker Daemon is Restarted
      service:
        name: docker
        state: restarted
      tags: [ 'restart-firewall' ]
