version: '3.3'

networks:
    underpass:
        external: true
    
volumes:
    droppy_config: {}
    droppy_files: {}
    heimdall_config: {}
    nginx-proxy-manager: {}
    softether_config: {}
    softether_packetlog: {}
    softether_securitylog: {}
    softether_serverlog: {}

services:
    mongo-express:
        image: mongo-express:0.54.0
        container_name: mongo-express
        restart: unless-stopped
        networks:
            - underpass
        ports:
            - "$MONGO_EXPRESS_PORT:8081"
        environment:
            - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_BASICAUTH_USERNAME=$MONGO_EXPRESS_USER
            - ME_CONFIG_BASICAUTH_PASSWORD=$MONGO_EXPRESS_PASSWORD

    droppy:
        image: silverwind/droppy:12.2.0
        container_name: droppy
        restart: unless-stopped
        networks: 
            - underpass
        ports:
            - "$DROPPY_PORT:8989"
        volumes:
            - droppy_config:/config
            - droppy_files:/files

    rdesktop:
        image: linuxserver/rdesktop
        container_name: rdesktop
        restart: unless-stopped
        privileged: true
        networks:
            - underpass
        ports:
            - "$RDESKTOP_PORT:3389"
        shm_size: "1gb"

    heimdall:
        image: linuxserver/heimdall:latest
        container_name: heimdall
        restart: unless-stopped
        networks:
            - underpass
        ports:
            - "$HEIMDALL_PORT:80"
            - "$HEIMDALL_PORT_HTTPS:443"
        volumes:
            - heimdall_config:/config

    nginx-proxy-manager:
        image: jlesage/nginx-proxy-manager:latest
        container_name: nginx-proxy-manager
        restart: unless-stopped
        networks:
            - underpass
        ports:
            - "8181:8181"
            - "80:8080"
            - "443:4443"
        volumes:
            - nginx-proxy-manager:/config
    
    softether:
        image: cenk1cenk2/softether-vpnsrv:v5.01.9674-5
        container_name: softether
        restart: unless-stopped
        privileged: true
        networks:
            - underpass
        ports:
            - "$SOFTETHER_IPSEC_PORT1_UDP:500/udp"
            - "$SOFTETHER_IPSEC_PORT2_UDP:4500/udp"
            - "$SOFTETHER_IPSEC_PORT3:1701"
            - "$SOFTETHER_OPENVPN_UDP:1194/udp"
            - "$SOFTETHER_OPENVPN_TCP:1194"
            - "$SOFTETHER_PORT1:1443"
            - "$SOFTETHER_PORT2:992"
            - "$SOFTETHER_PORT3:5555"
        environment:
            - TZ=$TZ
            - SRVIPSUBNET=$SRVIPSUBNET
            - SLEEPTIME=$SOFETHER_KEEP_ALIVE
            - KEEP_SERVER_LOG=$KEEP_SERVER_LOG
            - KEEP_PACKET_LOG=$KEEP_PACKET_LOG
            - KEEP_SECURITY_LOG=$KEEP_SECURITY_LOG
        volumes:
            - softether_config:/cfg
            - softether_packetlog:/etc/vpnserver/packet_log
            - softether_securitylog:/etc/vpnserver/security_log
            - softether_serverlog:/etc/vpnserver/server_log
        
